### ISSUE TITLE
Crashes with Fabric Loader 0.12

### ISSUE THREAD

**Issue by Fourmisain** [JamCoreModding/RightClickHarvestFabric#2]
Right clicking crops started crashing with the new loader:
> java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.setReturnValue(Object)" because "info" is null
	at net.minecraft.class_2302.handler$zho000$onUseMixin(class_2302.java:558)

This very much looks like a Mixin issue so I've reported it here: https://github.com/FabricMC/Mixin/issues/68

There is a workaround however and that is to add a reference to `info` inside the [currently empty `AbstractBlockMixin.onUseMixin()`](https://github.com/JamCoreModding/RightClickHarvestFabric/blob/e1dc1fc264b2576270c8cf6547b2960f19ee7f9c/src/main/java/io/github/jamalam360/mixin/AbstractBlockMixin.java#L43-L45), e.g. something like `throw new AssertionError(info);`
That seems to ensure that Mixin actually generates the `CallbackInfoReturnable` object and the cancelling logic, so maybe you wanna add that until the root cause is found.

**Comment by Jamalam360** [comment]
Thanks for this. I won't be able to fix anything until Friday as I'm away

**Comment by Fourmisain** [comment]
No problem, I wouldn't actually call this an issue until Fabric Loader 0.12 isn't called experimental anymore anyway.
Player just said it should be possible to fix this issue properly, so maybe this workaround won't be required afterall.

I also realize I wasn't thinking when I suggested `throw new AssertionError(info);` because that'd cause a crash when right clicking anything that's not a crop block (or any crop block that's not targeted by one of the mixins), a better workaround would be `info.getId();`, since it has no further side-effects.

**Comment by BrekiTomasson** [comment]
Any news on this?

**Comment by Jamalam360** [comment]
I could be wrong but I'm fairly certain this issue got fixed in floader

**Comment by Jamalam360** [comment]
![image](https://user-images.githubusercontent.com/56727311/139542795-1182af42-ef7c-4515-85c8-a9fad9efb59f.png)

It should be fixed, I'm unsure whether this has actually been released yet though

**Comment by Fourmisain** [comment]
The first PR aimed to fix it was released with 0.12.3 but it didn't solve the issue.
The new PR mentioned above was merged but isn't yet released.
This issue will likely be solved with 0.12.4, I'll test it once it releases.

**Comment by Jamalam360** [comment]
thanks

**Comment by Jamalam360** [comment]
![SmartSelect_20211030-220455_Discord.jpg](https://user-images.githubusercontent.com/56727311/139558341-fc500417-63f2-4760-a2cc-dd051e96cb66.jpg)

**Comment by Fourmisain** [comment]
Tested it in the dev env and (after clearing the gradle cache) it worked!

Gonna do some more testing tomorrow, but I'm pretty sure this can be considered fixed.

**Comment by Jamalam360** [comment]
Thanks for testing it :+1:
